apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    secret.reloader.stakater.com/reload: fiap/restaurante-acme
  namespace: fiap
  name: restaurante-acme
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurante-acme
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: restaurante-acme
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: product
                operator: In
                values:
                - fiap
      containers:
        - name: restaurante-acme
          image: developer0101/tech-challenge:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "512Mi"
              cpu: "256m"
          envFrom:
            - secretRef:
                name: restaurante-acme-secrets
            - configMapRef:
                name: restaurante-acme-vars
          readinessProbe:
              httpGet:
                  path: /v1/api/healthcheck
                  port: 8000
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 10
          livenessProbe:
              httpGet:
                  path: /v1/api/healthcheck
                  port: 8000
              initialDelaySeconds: 0
              timeoutSeconds: 1
              periodSeconds: 10
      imagePullSecrets:
        - name: default-secret
