
apiVersion: v1
kind: Secret
metadata:
  name: awssm-secret
  namespace: fiap
type: Opaque
data:
  access-key: QVNJQVk0TUdCV0NTWlA2WFpZWFk=
  secret-access-key: UdHSk9sTk01S1JwaklnVlZHSUozVTRCNGJFZmpiZmJ6WDZoZzF4ag==
  session-token: SVFvSmIzSnBaMmx1WDJWakVHTWFDWFZ6TFhkbGMzUXRNaUpHTUVRQ0lFQyt1MEVmQ05jN3MxbkhiSENwajA2NENmZ2greFlZN2pWMjlWNGVmM2dGQWlCNkd2bWNVTWUrL25FNEF6MTErTC9pNENiU1diUGtCVnpFTVZDbS9qNXI2Q3JDQWdpTS8vLy8vLy8vLy84QkVBSWFERFl4TURjd016TTFOakEyT1NJTVV1KzlsVXZWYUhtYSs0VTNLcFlDVy9HZW5rMWd5SENuUkV5RUVlYzZVYm9vVWtrUkJMcEZ6SUV3TndsS2cvWTEvekhVaVBTQ09QRGwrTjcvc2ZUdjlDTUZQQnF5QUhhUzdnNVE2UVFHeU5zYm5TVUxSSEpXSDZkVllVT2JkV0lFM0laMmpCY2h2NjIvRHEyeWIxbnFLRUhHZ3JBUDl4RDJZQm1lME43WHdFVWMyaUlhSjlTclI5aHJrR2xUZmxXVVNSSjg1N2taamJDSitTaHB2eFZ1aFhQRWlYaFVKZ0NrNU1ZUE9uSFF3TDlFSmgwTEwwRzZuY2pUYW1JRkZyVFhpKzRob29qNTVvOUF1cUdNY2dJR0xEdHY0ZmplRXJrTzM2a0puZGFoQ3BQQVVEZnRaNWZJR3g1RGhYL0Q5T3NLY3FBSnVkZ2RkWi9zSER2OXhsTlhXNUV5blhqdFdLQ3RseFdjQlNONXVMUm9wYWExZHkzd2YwRDU3MzJVbTBtUkx5YmRWNk13MWVPRnR3WTZuZ0VKSnFHc3RnNVNkTFVpakJPYnRFQnlvcTNFeXQxcVMzVk0rUWQ2TFZqWjFEWTduTEVMdXFyUkpQMTlSZmRBL2d4Ym9mZFZUMDhES2I2bHduQmlWdjRuMjVINkh2RmtLZzI5THBVNTloaTNwaTF2MGxSTnV6aW1namJVUzVteFp1Q0IzL25GY21hRGYwZWNkVnpIQUVjNXB0RURSWjZMeUpMMkxRZkNRWGFueFdFYjB0ZE5OQkdIbVM2Q3NwNGxBcUJQMG4zSjZTaEZjNUZFSS9xMlZnPT0=

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: restaurante-acme-secretstore
  namespace: fiap
spec:
  provider:
    aws:
      service: SecretsManager
      # define a specific role to limit access
      # to certain secrets.
      # role is a optional field that
      # can be omitted for test purposes
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
            namespace: fiap
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
            namespace: fiap
          sessionTokenSecretRef:
            name: awssm-secret
            key: session-token
            namespace: fiap

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: restaurante-acme-secrets
  namespace: fiap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: restaurante-acme-secretstore
  dataFrom:
    - extract:
        key: fiap/restaurante-acme-secrets
    - extract:
        key: fiap/restaurante-acme-database
  refreshInterval: 5m
  target:
    creationPolicy: Owner
    deletionPolicy: Retain

