
apiVersion: v1
kind: Secret
metadata:
  name: awssm-secret
  namespace: fiap
type: Opaque
data:
  access-key: QVNJQVk0TUdCV0NTWVpGV1lQTzc=
  secret-access-key: LzNIWWNTQUxEdnlNTnF2M1JwNnE5WE45TkZpU0VHeS94ZTcrbVhHSg==
  session-token: SVFvSmIzSnBaMmx1WDJWakVETWFDWFZ6TFhkbGMzUXRNaUpITUVVQ0lDdlNQb2FjRzFBOUlUMUEzTmozSWxkSnlBWlQra2lhZHBtZml5cm1KZW9KQWlFQXFZaGRVaFJ6OHBoZXhrc0hNK0MzSm9oY0xVWVN1TDJTSllvcmxlcHplZ0VxdVFJSVhCQUNHZ3cyTVRBM01ETXpOVFl3TmpraURJaExOek8xcUhiLzVjNzMzU3FXQW9jcVhRbGdERWVOZEtzWFFSVTRLZDd5MFdqWWpqYUFIYWtaWDBabENBdG1KTkxTcUVobGpXSEE0N011UUd4cmVJZzBQdE5pZGQ0anQ1b1RuMXFIcWhaWjJqK2g3K0RlRE9pL1JYazlDTGtOVFJKa0xma3cvUWhMK0hwTWNOZUFpQlhVdlJxeDdIOGdUcWI3ZTBrMXBMZVAwVThMbDl0dlIwTVFIeE90c0NLU3BORHBPZFFhKzBKUmlFaEZEUkpNVCs5U3g5bGtNRS9IUGZVaE9OS0wrMHZ1eE1uNnRIVEdCYWh2eHBwK1lVRnlzd0ZCaTV0NHFmbTZFOWJOL0hvdS8wdTZqSHRycmtIaEs1YUtoTWNKNTlKdlRxanZtcUhLRjA5WnZ6QjduMzV6aGE2TGhqRVJwYTJPem93YzlUNnRVMmlIcThWSENOYkppd1lSb3NnZUc0TTlHb0EzVmxHUVp2bEVJa1FhQTY2SnZtMklzK0pmTU95Yis3WUdPcDBCQkMvZzhkQlF3RndEWW52NEZhNGFMTVJGTVJudWc5YUNYejhnYjB0aG96RnRvVUttVEJmSGZiYXVEOWxWYzlXUEV6c0pxakNnYVRvK1UzN3pwZ1BDbnAyOEVXTXJTYmdTb3JHcC9RdUU0ZVMvRTZ5U0RGdDRXU2lmQitVZ3lWK0g0Y0ZVWFBXdXBNVXhyMHRkcFVGbnFoanV1TWZXMzRtNVNCUVFOWGY3NHRRMnp1aWVoUE9vakFHZlQvcmg1KzFMQ0JvNzQ4T01xYUZSVVo0WFF3PT0=

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: restaurante-acme-secretstore
  namespace: fiap
spec:
  provider:
    aws:
      service: SecretsManager
      # define a specific role to limit access
      # to certain secrets.
      # role is a optional field that
      # can be omitted for test purposes
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
            namespace: fiap
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
            namespace: fiap
          sessionTokenSecretRef:
            name: awssm-secret
            key: session-token
            namespace: fiap

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: restaurante-acme-secrets
  namespace: fiap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: restaurante-acme-secretstore
  dataFrom:
    - extract:
        key: fiap/restaurante-acme-secrets
    - extract:
        key: fiap/restaurante-acme-database
  refreshInterval: 5m
  target:
    creationPolicy: Owner
    deletionPolicy: Retain

