apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: fiap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: developer0101
            - name: MYSQL_USER
              value: developer0101
            - name: MYSQL_PASSWORD
              value: developer0101
            - name: MYSQL_DATABASE
              value: developer0101
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "false"
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "512Mi"
              cpu: "256m"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
