apiVersion: v1
kind: Service
metadata:
  namespace: $K8S_NAMESPACE
  name: $K8S_APPLICATION_NAME-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      name: app
  type: ClusterIP
  selector:
    app: $K8S_APPLICATION_NAME
