name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Resolve vars
        env:
          TESTE: ${{secrets.AWS_ACCESS_KEY_ID}}
        run: |
          echo "$TESTE"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      # - name: Run ESLint
      #   run: npm run lint

      # - name: Run Prettier Check
      #   run: npm run prettier:check

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test -- --coverage

  build_and_push_ecr:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git variables
        id: vars
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
          SHORT_SHA=$(echo "${GITHUB_SHA::7}")
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create ECR Repository if not exists
        run: |
          aws ecr describe-repositories --repository-names "${{ env.BRANCH_NAME }}" || \
          aws ecr create-repository --repository-name "${{ env.BRANCH_NAME }}"

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ env.SHORT_SHA }}
          REPO_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.BRANCH_NAME }}
          docker build -t $REPO_URI:$IMAGE_TAG .

      - name: Push Docker Image to ECR
        run: |
          IMAGE_TAG=${{ env.SHORT_SHA }}
          REPO_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.BRANCH_NAME }}
          docker push $REPO_URI:$IMAGE_TAG

  deploy_eks:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build_and_push_ecr
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git variables
        id: vars
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
          SHORT_SHA=$(echo "${GITHUB_SHA::7}")
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS cluster
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Set Kubernetes context to the EKS cluster
        run: kubectl config use-context arn:aws:eks:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:cluster/${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy Kubernetes resources
        run: |
          kubectl set image -f k8s/ --all "*=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.BRANCH_NAME }}:${{ env.SHORT_SHA }}"
          kubectl apply -f k8s/
